### ISSUE TITLE
Beta won’t load

### ISSUE THREAD

**Issue by fnfporterhi** [realDunkin/fnfmegapack-html5#5]
I get “this webpage reloaded because a problem occurred”, and I have a RTX 3090, and it still says “This webpage was reloaded because a problem occurred.”

**Comment by realDunkin** [comment]
The beta version is known for doing this, you can try the beta test version, which has fixed this issue and will be fixed when the new update releases (https://realdunkin.github.io/fnfmegapack-html5-test/)

**Comment by fnfporterhi** [comment]
Ok thx
